upstream svg_draw_upstream {
    zone svg_draw_upstream 64k;
    server svg-draw:80 resolve;
    keepalive 16;
}

upstream siye_world_upstream {
    zone siye_world_upstream 64k;
    server siye-world:80 resolve;
    keepalive 16;
}

upstream music_api_upstream {
    zone music_api_upstream 64k;
    server music-api:3000 resolve;
    keepalive 16;
}

upstream linux_server_upstream {
    zone linux_server_upstream 64k;
    server linux-server:8081 resolve;
    keepalive 16;
}

upstream easy_chat_upstream {
    zone easy_chat_upstream 64k;
    server easy-chat:3030 resolve;
    keepalive 16;
}

upstream sub2api_upstream {
    zone sub2api_upstream 64k;
    server sub2api:8080 resolve;
    keepalive 16;
}

upstream knowledge_upstream {
    zone knowledge_upstream 64k;
    server knowledge:3001 resolve;
    keepalive 16;
}
